@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(customer, "Клиент", "оформляет заявку на платформе")
Person(manager, "Сотрудник", "сотрудник банка")

System_Boundary(icompanysystem, "Платформа") {

System(cabinet, "Сервис Факторинга", "")
System(offers, "Модуль заявок", "")
System(settlemenets, "Модуль расчетов", "Баланс, расчеты, безопасные сделки")
System(edm, "Модуль ЭДО", "Онлайн договора, акты")
System(factcalc, "Модуль подбора продукта", "Калькулатор параметров факторинга")
System(dossier, "Модуль Досье", "Досье заявки")

'System(videochat, "Видеочат", "Собственная разработка")

System(docclassifier, "Распознаватель документов", "Классифицирует и считывает данные со сканов")

System(docgen, "Генератор документов", "Генератор печатных форм")

Rel(customer, cabinet, "Заводит заявку", "web-интерфейс")

Rel(manager, cabinet, "Работает с заявкой", "web-интерфейс")

Rel(settlemenets, cabinet, "Отражает баланс и расходы")
Rel(edm, cabinet, "Отражает текущие договора")
Rel(factcalc, cabinet, "Позволяет рассчитать продукт")

System(messaging, "Модуль коммуникации", "Коммуникация по различным каналам")
Rel(cabinet,messaging,"Осуществляет коммуникацию с клиентами")

Rel(offers, cabinet, "Отражает текущие заявки")

'Rel(manager, factcalc, "Подбирает продукт")
'Rel(customer,factcalc, "Подбирает продукт")

'Rel(cabinet, videochat, "Видеозвонки из платформы")

Rel(cabinet,dossier,"Хранит досье заявки")

Rel(dossier,docclassifier,"Классификация и распознавание сканов")

Rel(dossier,docgen, "генерирует договора, акты и другие документы")

}

System(sed, "СЭД", "Сервис ЭДО Банка, Диадок, ГосКлюч и т.д.")
Rel(edm,sed,"Получает и отправляет документы на подпись")

System(absbank, "АБС Банка", "АБС Банка")

System(bpm, "РКО", "BPM модуль  Банка")
Rel(offers,bpm, "Создает бизнес-процессы в Банке")

System(ehd,"Электронное хранилище документов Банка")
Rel(dossier,ehd,"Выгружает документы в ЭХД Банка")

Rel(settlemenets, absbank,"Получает выписки, выгружает платежи", "kafka")
System(recognition, "Сервис распознавания документов Банка")
Rel(docclassifier, recognition, "Распознает документы")


System(messagingbank, "Оркестратор коммуникация с клиентами", "sms, e-mail, контакт центр")
Rel(messaging,messagingbank,"Отправляет сообщения клиентам")
System(opendata,"Открытые источники данных", "ФНС, ФССП, МВД, ЕФРС о банкротстве")
Rel(cabinet,opendata,"Получает данные по клиенту")

System(oidcbankclient, "Сервис авторизации клиента Банка")
Rel(cabinet,oidcbankclient,"Авторизует клиента банка")

System(oidcbankstaff, "Сервис авторизации сотрудника Банка")
Rel(cabinet,oidcbankstaff,"Авторизует сотрудника банка")


System(bibank, "BI Система Банка")
Rel(cabinet,bibank,"Выгружает данные в BI")

@enduml